[server]
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#2563eb"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#eeeeee"
textColor = "#1f2937"
